// Package static Code generated by swaggo/swag. DO NOT EDIT
package static

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/rooms": {
            "get": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Retreive list of all rooms that calling user is a member of.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "List rooms",
                "parameters": [
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "1",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "20",
                        "description": "Rooms per page",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "members",
                        "description": "Additional objects to be included in the response",
                        "name": "include",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.RoomsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Create a room and return the created room. Calling user is added as an ADMIN in the room.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Create a room",
                "parameters": [
                    {
                        "description": "Room Request",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateRoomBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.RoomResponse"
                        }
                    }
                }
            }
        },
        "/v1/rooms/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Get a single room by its id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Get room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.RoomResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Delete a room. Calling user should be an ADMIN in the room.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Delete a room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Update a room and return the updated room. Calling user should be an ADMIN in the room.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Update a room",
                "parameters": [
                    {
                        "description": "Room Request",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateRoomBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.RoomResponse"
                        }
                    }
                }
            }
        },
        "/v1/rooms/{roomID}/messages": {
            "get": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "List messages in a room. Returns all SENT messages in the room along with drafts created by the calling user in descending order of modified time. Calling user should be a member in the room.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "List messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Room id of the room in which message is added",
                        "name": "roomID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Modified date time upto which messages should be returned",
                        "name": "modifiedBefore",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessagesResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Create a message in the specified room and return the created message. Calling user should be a member in the room. Calling user is added as message sender.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Create a message",
                "parameters": [
                    {
                        "description": "Message Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Room id of the room in which message is added",
                        "name": "roomID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    }
                }
            }
        },
        "/v1/rooms/{roomID}/messages/messageID": {
            "delete": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Delete a message. Message should be a DRAFT and Calling user should be the sender of the message.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Delete a message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Room id of the room in which message is added",
                        "name": "roomID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Message id",
                        "name": "messageID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Update a message and return the update message. Message should be a DRAFT and Calling user should be the sender of the message.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Update a message",
                "parameters": [
                    {
                        "description": "Message Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Room id of the room in which message is added",
                        "name": "roomID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Message id",
                        "name": "messageID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "get": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Retreive list of all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 20,
                        "description": "Users per page",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UsersResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Create a new user and return the created user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create a user",
                "parameters": [
                    {
                        "description": "User Request",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UserBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Delete a user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "Update a user and return the updated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "description": "User Request",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UserBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "External identifier of the user",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Message content",
                    "type": "string",
                    "example": "Hello"
                },
                "createdAt": {
                    "description": "Time when entity was created",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "deletedAt": {
                    "description": "Time when entity was deleted",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "id": {
                    "description": "Unique identifier of the message",
                    "type": "string",
                    "example": "89e48f30"
                },
                "modifiedAt": {
                    "description": "Time when entity was modified",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "roomID": {
                    "description": "Unique identifier of the room that message is added to",
                    "type": "string",
                    "example": "89e47f30"
                },
                "senderID": {
                    "description": "Unique identifier of the user that created the message",
                    "type": "string",
                    "example": "89e46f30"
                },
                "sentAt": {
                    "description": "Time when the message was sent. Is null for Drafts",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "status": {
                    "description": "Status of the message",
                    "allOf": [
                        {
                            "$ref": "#/definitions/message.Status"
                        }
                    ],
                    "example": "SENT"
                }
            }
        },
        "entities.Room": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Time when entity was created",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "deletedAt": {
                    "description": "Time when entity was deleted",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "id": {
                    "description": "Unique identifier of the room",
                    "type": "string",
                    "example": "89e47f30"
                },
                "isGroup": {
                    "description": "Indicates if the room is a group. Is false for chats.",
                    "type": "boolean",
                    "example": true
                },
                "members": {
                    "description": "List of room members",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.RoomMember"
                    }
                },
                "modifiedAt": {
                    "description": "Time when entity was modified",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "name": {
                    "description": "Name of the room",
                    "type": "string",
                    "example": "Friends"
                }
            }
        },
        "entities.RoomMember": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Time when entity was created",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "deletedAt": {
                    "description": "Time when entity was deleted",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "modifiedAt": {
                    "description": "Time when entity was modified",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "role": {
                    "description": "Role defines permissions of user on the room.",
                    "enum": [
                        "ADMIN",
                        "MEMBER"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/roommember.Role"
                        }
                    ],
                    "example": "ADMIN"
                },
                "roomID": {
                    "description": "Unique identifier of the room",
                    "type": "string",
                    "example": "89e47f30"
                },
                "userID": {
                    "description": "External identifier of the user",
                    "type": "string",
                    "example": "89e46f30"
                }
            }
        },
        "entities.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Time when entity was created",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "deletedAt": {
                    "description": "Time when entity was deleted",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "id": {
                    "description": "External identifier of the user",
                    "type": "string",
                    "example": "89e46f30"
                },
                "modifiedAt": {
                    "description": "Time when entity was modified",
                    "type": "string",
                    "example": "2025-02-08T14:13:39.080551Z"
                },
                "name": {
                    "description": "Name of the user",
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "handlers.CreateRoomBody": {
            "type": "object",
            "required": [
                "members"
            ],
            "properties": {
                "members": {
                    "description": "List of user ids of room members.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "89e46f31",
                        "89e46f32"
                    ]
                },
                "name": {
                    "description": "Optional group name",
                    "type": "string",
                    "example": "Friends"
                },
                "roomID": {
                    "description": "Optional unique identifier of the room. A default UID is created if not present",
                    "type": "string",
                    "example": "89e47f30"
                }
            }
        },
        "handlers.MessageBody": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Message content",
                    "type": "string",
                    "example": "Hello"
                },
                "status": {
                    "description": "Message status",
                    "default": "DRAFT",
                    "enum": [
                        "DRAFT",
                        "SENT"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/message.Status"
                        }
                    ],
                    "example": "SENT"
                }
            }
        },
        "handlers.MessageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/entities.Message"
                }
            }
        },
        "handlers.MessagesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Message"
                    }
                }
            }
        },
        "handlers.RoomResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/entities.Room"
                }
            }
        },
        "handlers.RoomsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Room"
                    }
                }
            }
        },
        "handlers.UpdateRoomBody": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Updated group name",
                    "type": "string",
                    "example": "Friends"
                }
            }
        },
        "handlers.UserBody": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the user",
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "handlers.UserResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/entities.User"
                }
            }
        },
        "handlers.UsersResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.User"
                    }
                }
            }
        },
        "message.Status": {
            "type": "string",
            "enum": [
                "DRAFT",
                "SENT"
            ],
            "x-enum-varnames": [
                "StatusDraft",
                "StatusSent"
            ]
        },
        "roommember.Role": {
            "type": "string",
            "enum": [
                "ADMIN",
                "MEMBER"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleMember"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKey": {
            "type": "apiKey",
            "name": "X-API-KEY",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
